[package]
name = "lazy_bundle"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "ecs"]
categories = ["game-development"]
repository = "https://github.com/ickshonpe/lazy_bundle"

[dependencies.bevy]
version = "0.8"
default-features = false